### ISSUE TITLE
Crash with Actually Additions

### ISSUE THREAD

**Issue by Fortist** [Selim042/ModJam_5#1]
Was looking forward to this mod, man.

https://pastebin.com/SzUSSZLZ

**Comment by Selim042** [comment]
I think I see the problem already.  I will further investigate later.

**Comment by Selim042** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crash with Actually Additions](https://trello.com/c/E2IL9oub/9-crash-with-actually-additions)

**Comment by Selim042** [comment]
How would I reproduce this crash?  Is it upon loading or when doing something specific?

**Comment by Selim042** [comment]
In the future I recommend providing more details in your initial issue report.  I may have fixed it, but I am unsure and cannot check as I do not know how to replicate your issue.  I pushed an update to [CurseForge](https://minecraft.curseforge.com/projects/selims-backpacks).

**Comment by Selim042** [comment]
Very strange, I was using AA w/ this earlier and never found an issue, probably not their fault, they are just getting pulled in.  Anyways, I cannot seem to replicate this bug, so please let me know if the latest update (1.1.2) on CurseForge fixes it for you.

**Comment by Fortist** [comment]
It works.

**Comment by Selim042** [comment]
Thanks for the help. I have a but of advice, next time you need to submit an issue report (for anyone's project), please provide as much information as you can initially, and what the person you are reporting to needs to know. It saves a lot of time in the process.
