### ISSUE TITLE
#3 some more issues and a suggestion

### ISSUE THREAD

**Issue by exceptionofend** [Selim042/ModJam_5#3]
YES it totally does remove Enchantments/Energy and dmg values :)
https://gyazo.com/2ad1556aa768219854f6d553479b7b73

would it be possible to make the ender upgrade be craftable with the ender storage ender chest to match those
so basicly just the upgrade on its on links to the vanila ender chest and adding an enderchest from ender storage does link it to the chest with the coulor code

**Comment by Selim042** [comment]
Yep, that is the main issue in the other report, making this a duplicate.  I just realized I never added a recipe for the Ender Upgrade.  I'll push an update for that shortly.  You can right click an Ender Upgrade on an Ender Storage Ender Chest to bind it though.
