### ISSUE TITLE
loosing inventory

### ISSUE THREAD

**Issue by exceptionofend** [Selim042/ModJam_5#4]
if you have stuff in the inventory and put of the chestplate and back on all your stuff is gone (inside the chestplate)

you should also make a kind off toolbelt maybe that similar to the chest just for the legging since playing with modded minecraft adds a lot of tools wrenches and so on so maybe you can store in the leggins tools and the chestplate is for example mining

**Comment by exceptionofend** [comment]
also closing the game and restarting it seems to delete everything in the chestplate

**Comment by exceptionofend** [comment]
What you expected to happen:
Item should still be in the inventory.

Steps to reproduce:
Open the inventory ui via hotkey, put something in close ui, take off the chestplate for a secound reopen ui and its gone (it also happens when restarting the game without any crash reports tho, weirdly enough is also resets my keybinding for the ui)

https://gyazo.com/b062ecbb23dffe3157257d3671e122f4

(this also happens with other chestplates)

Version (make sure you are on the latest version before reporting):
Minecraft: 1.12.2
Forge: 14.23.2.2618
SelimsBackpacks 1.12.2 V1.1.1

Does this issue occur on a server? [yes/no]
no... single player world.

**Comment by Selim042** [comment]
Did you attempt to close and reopen the inventory after you encountered this issue?

**Comment by bobfrapples49** [comment]
I too am experiencing this, now on the 1.1.2 version. Any time the chestpiece is removed, all upgrades and inventory disappear. This is on the one uploaded about an hour ago.

**Comment by Selim042** [comment]
Are you in creative or survival? If creative, that is an issue in MinecraftForge/MinecraftForge#4580, and no solvable by me. If you are still experiencing this in survival, please activate verbose mode in the config and upload a log to [Gist](gist.github.com) or [Pastebin](pastebin.com) for me to review.

**Comment by Fortist** [comment]
In both creative and survival do you lose the inventory.
I guess Ill try the verbose thing later.

**Comment by Selim042** [comment]
@bobfrapples49 Have you had a chance to take a look if the issue you are experiencing is creative, survival, or both?

@Fortist Have you had a chance to enable verbose mode and gather a log?

**Comment by bobfrapples49** [comment]
Here's the log. It's both creative and survival. Interestingly, it seems I was mistaken and the upgrade held. but the three items inside did not. 
https://gist.github.com/bobfrapples49/9cf3dedafe636a2f54e1e7b8dd74d663#file-bobsbackpacklog

**Comment by Selim042** [comment]
I think I finally got it figured out.  Sorry about the slow progress, this is my first time working with my own item capabilities.  I'm will be uploading version 1.1.3 to CurseForge soon.

**Comment by Selim042** [comment]
The update on CurseForge has been approved, this should be solved now.  If you still have any issues, please reopen this issue.
