### ISSUE TITLE
Keybind Resets

### ISSUE THREAD

**Issue by Fortist** [Selim042/ModJam_5#7]
Quitting and coming back resets the keybind to the default.

**Comment by Selim042** [comment]
Please use the issue template.

**Comment by Fortist** [comment]
"No"

Also, I have "Controlling" if that does anything.
May just set my controls to read only, for now.

**Comment by Selim042** [comment]
I need the information requested in the issue template.  It makes it hard to help you if I don't have enough information.

**Comment by Selim042** [comment]
@Fortist 
I need to know what versions of everything you have to see what I can do and try to track down the problem.  It makes it hard to solve if I don't have that information.
