### ISSUE TITLE
Modified key bindings revert to default on client restart.

### ISSUE THREAD

**Issue by CplPibald** [Selim042/ModJam_5#8]
> Your issue may already be reported!

**Issue was [reported](https://github.com/Selim042/ModJam_5/issues/7), but does not appear to have been investigated.**

## Steps to Reproduce (for bugs)
1. Go into Minecraft Options->Controls menu and change "Open Backpack" keybind from default ('G') to any other key (eg: 'F')
2. Close Minecraft and restart.

## Expected Behavior
After restart, "Open Backpack" is bound to 'F' key.

## Current Behavior
"Open Backpack" is bound to default 'G' key.

## Possible Solution
I'm not sure what the root cause is.  The new binding is being written to options.txt, but after restart, opening the config menu causes options.txt to revert back to defaults for these settings. A very similar bug was found and fixed here: https://github.com/pau101/Wings/issues/1

## Context
> How has this issue affected you? What are you trying to accomplish?

The effect is that players who don't use the default keys have to change the keybind every time they launch the game.

## Your Environment
* Selim's Backpacks version: 1.12.2-1.1.3
* Forge version: 14.23.4.2760
* Optifine?: no
* Minecraft version: 1.12.2

**Comment by Selim042** [comment]
I'll try and look into it when I get a chance.  I'm not as familiar with registering keybinds so I will do what I can.

In regards to why nothing was done previously, I did not have enough information to do much about it nor did the reporter want to give said information.

**Comment by Selim042** [comment]
Not stale, just not working on the project

**Comment by MrNerdy42** [comment]
In an attempt to ward off the evil and cunning stale bot, I'm letting you know that this issue still persists. I looked at your code and it seems that the only difference between it and the keybinding code in my own mod is that your variables are `static final` whereas mine are only `static`

**Comment by Selim042** [comment]
Thanks, I will take a look at that.  Right now I am slowing working on porting my smaller mods to 1.13 and I'm not sure that I will focus too much on strange bug fixes with them.  School, work, and other projects have been taking a higher priority recently.

**Comment by MrNerdy42** [comment]
Totally understandable. I'm in school as well and can definitely relate. Good luck to yah!
